#!/usr/bin/env sh
# Copyright (c) 2015 Damian Janowski

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.



ENTRY=$1

m4 -P -D__file="$ENTRY" -I "$(dirname "$ENTRY")" - << 'EOS'
m4_define(`set',      `m4_define(`$1', `$2')')
m4_define(`on',       `m4_divert'($1)`__selector {')
m4_define(`end',      `}m4_divert(0)')
m4_define(`selector', `m4_define(`__selector', '$1`)$1')
m4_define(`include',  `m4_include('$1`)')
m4_changecom(`/*', `*/')

m4_define(`__last_breakpoint', 0)

m4_define(`breakpoint', `
  m4_define(`__last_breakpoint', m4_incr(__last_breakpoint))
  m4_define($1, __last_breakpoint)
  m4_define(`__breakpoint_'$1`', `$2')
')

m4_include(__file)

m4_define(`__print_breakpoints', `m4_ifdef(`__breakpoint_$1', `
@media only screen and (__breakpoint_$1) {
  m4_undivert($1)
}
__print_breakpoints(m4_incr($1))
')')

__print_breakpoints(1)
EOS
